// Package cmcloud provides an interface to China Mobile Cloud (中国移动云盘/和彩云)
// via the IDaaS open platform API (openapi.yun.139.com V3 网关).
//
// 协议事实均经真实凭据实测。root 一律锚定智能体专属目录
// （user/folder/query 返回的 folderId），不做全盘读写；删除/移动/改名
// 端点被服务端按 skillId 屏蔽（一律返回 01000005），相应接口不实现。
package cmcloud

import (
	"context"
	"errors"
	"fmt"
	"io"
	"net/http"
	"path"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
	"github.com/rclone/rclone/backend/cmcloud/api"
	"github.com/rclone/rclone/fs"
	"github.com/rclone/rclone/fs/config"
	"github.com/rclone/rclone/fs/config/configmap"
	"github.com/rclone/rclone/fs/config/configstruct"
	"github.com/rclone/rclone/fs/fserrors"
	"github.com/rclone/rclone/fs/fshttp"
	"github.com/rclone/rclone/fs/hash"
	"github.com/rclone/rclone/fs/list"
	"github.com/rclone/rclone/lib/dircache"
	"github.com/rclone/rclone/lib/encoder"
	"github.com/rclone/rclone/lib/rest"
)

// 上传分片约束（服务端硬性限制）：
// 非末片不得小于 5MiB，partNumber 1~10000 连续递增，单批不超过 100 片。
// 分片规划保证总片数不超过 100（片数超限时增大单片），因此 create 响应
// 直接携带全部分片地址，getUploadUrl 补取路径在本规划下不可达。
const (
	minChunkSize    = 5 * 1024 * 1024
	defaultCutoff   = 5 * 1024 * 1024
	defaultChunk    = 32 * 1024 * 1024
	copyLocateTries = 3 // 服务端复制后短暂可见性延迟的重试次数
)

func init() {
	fs.Register(&fs.RegInfo{
		Name:        "cmcloud",
		Description: "China Mobile Cloud (中国移动云盘)",
		NewFs:       NewFs,
		Config:      Config,
		Options: []fs.Option{{
			Name:      "access_token",
			Help:      "Long-term access token from the IDaaS authorization - set by the config wizard.",
			Hide:      fs.OptionHideBoth,
			Sensitive: true,
		}, {
			Name: "claw_uid",
			Help: `Device identity (clawUid) bound to the authorization.

Generated by the config wizard on first authorization and bound to
the access_token on the server side. Keep it unchanged to keep the
same dedicated directory.`,
			Hide: fs.OptionHideBoth,
		}, {
			Name:     "upload_cutoff",
			Help:     "Cutoff for switching to multipart upload (>= 5 MiB).",
			Default:  fs.SizeSuffix(defaultCutoff),
			Advanced: true,
		}, {
			Name:     "chunk_size",
			Help:     "Chunk size for multipart upload (>= 5 MiB).\n\nFiles larger than upload_cutoff are split into chunks of this size. The number of parts is capped at 100; larger files get proportionally larger parts.",
			Default:  fs.SizeSuffix(defaultChunk),
			Advanced: true,
		}, {
			Name:     config.ConfigEncoding,
			Help:     config.ConfigEncodingHelp,
			Advanced: true,
			// 平台禁止的文件名字符 \/:*?"<>| 由 EncodeWin/EncodeBackSlash 覆盖。
			// EncodeDot/EncodeSlash 必须保留：encoder 的 Standard 层会把全角
			// 点/斜杠解码回 ASCII，前者被 path.Join 清洗后会让 create 落在父
			// 目录上替换掉整个目录（baidupcs 交付时的实测事故），后者会分裂
			// 路径。前导空格会被服务端裁剪（fstests 实测），尾部空格与尾部
			// 点按往返一致性编码。
			Default: (encoder.EncodeWin | // :?*<>| 平台禁止的文件名字符
				encoder.EncodeBackSlash |
				encoder.EncodeDot |
				encoder.EncodeSlash |
				encoder.EncodeLeftSpace | // 服务端裁剪前导空格（fstests 实测）
				encoder.EncodeRightSpace |
				encoder.EncodeRightPeriod |
				encoder.EncodeCtl |
				encoder.EncodeDel |
				encoder.EncodeInvalidUtf8),
		}},
	})
}

// Options defines the configuration for this backend.
type Options struct {
	AccessToken  string               `config:"access_token"`
	ClawUID      string               `config:"claw_uid"`
	UploadCutoff fs.SizeSuffix        `config:"upload_cutoff"`
	ChunkSize    fs.SizeSuffix        `config:"chunk_size"`
	Enc          encoder.MultiEncoder `config:"encoding"`
}

// Fs represents a remote cmcloud dedicated directory.
type Fs struct {
	name     string             // name of this remote
	root     string             // root path within the dedicated directory
	opt      Options            // parsed options
	features *fs.Features       // optional features
	c        *api.Client        // business API client
	auth     *api.Auth          // ticket manager
	pacer    *fs.Pacer          // pacer for API calls
	client   *http.Client       // for presigned PUT/GET transfers
	dirCache *dircache.DirCache // path -> fileId cache
}

// Object describes a cmcloud object.
type Object struct {
	fs          *Fs       // what this object is part of
	remote      string    // remote path
	hasMetaData bool      // whether info below has been set
	id          string    // fileId of the object
	size        int64     // size of the object
	modTime     time.Time // modification time of the object
	sha256      string    // content hash from the server
}

// ------------------------------------------------------------

// Name of the remote (as passed into NewFs)
func (f *Fs) Name() string {
	return f.name
}

// Root of the remote (as passed into NewFs)
func (f *Fs) Root() string {
	return f.root
}

// String converts this Fs to a string
func (f *Fs) String() string {
	return fmt.Sprintf("cmcloud dedicated directory root '%s'", f.root)
}

// Features returns the optional features of this Fs
func (f *Fs) Features() *fs.Features {
	return f.features
}

// Precision return the precision of this Fs.
// 服务端时间为毫秒精度；ModTime 只读（update 端点被屏蔽）。
func (f *Fs) Precision() time.Duration {
	return time.Millisecond
}

// Hashes returns the supported hash sets.
// 云空间底座提供 sha256（真实凭据实测确认）。
func (f *Fs) Hashes() hash.Set {
	return hash.Set(hash.SHA256)
}

// ------------------------------------------------------------

// newAuthSrv 为 config 向导构造独立的认证通道 client。
func newAuthSrv(ctx context.Context) *rest.Client {
	return rest.NewClient(fshttp.NewClient(ctx)).SetRoot(api.TokenBaseURL)
}

// wizardSessions 保存向导两次状态调用之间的授权会话（uuid 与授权页
// 地址），按 remote 名隔离。uuid 是授权环第二步 preAuth 的必备参数，
// 不能落盘（它属于一次性会话）。
var wizardSessions sync.Map

type wizardSession struct {
	uuid        string
	authPageURL string
}

// Config is the state machine for `rclone config`：
// 生成/复用 clawUid → preAuth（不带 uuid）→ 展示 authPageUrl →
// 用户浏览器完成授权后按回车 → preAuth（带 uuid）→ 103000 →
// access_token 与 claw_uid 写入配置。
func Config(ctx context.Context, name string, m configmap.Mapper, conf fs.ConfigIn) (*fs.ConfigOut, error) {
	switch conf.State {
	case "":
		rawToken, _ := m.Get("access_token")
		clawUID, _ := m.Get("claw_uid")
		// 已有凭据时先静默验证，避免每次 config 都强制重授权
		if rawToken != "" && clawUID != "" {
			srv := newAuthSrv(ctx)
			auth := api.NewAuth(rawToken, clawUID, srv)
			result, err := auth.PreAuth(ctx, "")
			if err == nil && result.ResultCode == "103000" {
				if result.AccessToken != "" {
					m.Set("access_token", result.AccessToken)
				}
				return nil, nil
			}
			// 验证失败（token 失效或网络错误）：继续走重新授权流程，
			// 保留原 clawUID 以维持专属目录不变
			if err != nil {
				fs.Debugf(nil, "cmcloud: silent token check failed: %v", err)
			}
		}
		if clawUID == "" {
			clawUID = uuid.NewString()
			m.Set("claw_uid", clawUID)
		}
		// 重新授权时不携带旧 accessToken（SDK 在 103001 后同样清空它）
		srv := newAuthSrv(ctx)
		auth := api.NewAuth("", clawUID, srv)
		result, err := auth.PreAuth(ctx, "")
		if err != nil {
			return nil, fmt.Errorf("cmcloud: preAuth failed: %w", err)
		}
		switch result.ResultCode {
		case "103000":
			// 不应出现（无 accessToken 时服务端要求授权），防御性处理
			if result.AccessToken != "" {
				m.Set("access_token", result.AccessToken)
				return nil, nil
			}
			return nil, errors.New("cmcloud: preAuth returned success without access token")
		case "103001":
			if result.AuthPageURL == "" || result.UUID == "" {
				return nil, errors.New("cmcloud: preAuth response missing authPageUrl or uuid")
			}
			wizardSessions.Store(name, &wizardSession{uuid: result.UUID, authPageURL: result.AuthPageURL})
			return fs.ConfigInput("auth_wait", "config_auth_wait", authPrompt(result.AuthPageURL))
		default:
			return nil, fmt.Errorf("cmcloud: preAuth returned %s (%s)", result.ResultCode, result.Desc)
		}
	case "auth_wait":
		clawUID, _ := m.Get("claw_uid")
		if clawUID == "" {
			return nil, errors.New("cmcloud: claw_uid is missing - restart `rclone config`")
		}
		var session *wizardSession
		if v, ok := wizardSessions.Load(name); ok {
			session = v.(*wizardSession)
		}
		if session == nil || session.uuid == "" {
			return fs.ConfigError("", "authorization session lost - restart `rclone config`")
		}
		srv := newAuthSrv(ctx)
		auth := api.NewAuth("", clawUID, srv)
		result, err := auth.PreAuth(ctx, session.uuid)
		if err != nil {
			return fs.ConfigError("auth_wait", "preAuth failed: "+err.Error())
		}
		switch result.ResultCode {
		case "103000":
			wizardSessions.Delete(name)
			if result.AccessToken == "" {
				return fs.ConfigError("auth_wait", "preAuth success but no access token in response - restart `rclone config`")
			}
			m.Set("access_token", result.AccessToken)
			return nil, nil
		case "103001":
			// 会话被服务端作废，换新入口重试
			if result.AuthPageURL == "" || result.UUID == "" {
				return fs.ConfigError("auth_wait", "preAuth response missing authPageUrl or uuid")
			}
			wizardSessions.Store(name, &wizardSession{uuid: result.UUID, authPageURL: result.AuthPageURL})
			return fs.ConfigError("auth_wait", "The previous authorization session was invalidated. Open the new URL below, finish the authorization, then press Enter again.\n\n"+result.AuthPageURL)
		case "130088":
			// 会话未完成授权：重放同一入口（实测出现过用户自认已授权但
			// 服务端仍回 130088 的情况，须走到页面最终成功提示）
			return fs.ConfigError("auth_wait", "The authorization is not finished yet. Make sure the page opened from the URL below reaches its final success message, then press Enter again.\n\n"+session.authPageURL)
		default:
			return fs.ConfigError("auth_wait", fmt.Sprintf("preAuth returned %s (%s)", result.ResultCode, result.Desc))
		}
	}
	return nil, fmt.Errorf("cmcloud: unknown config state %q", conf.State)
}

// authPrompt 生成授权页提示文案。
func authPrompt(authPageURL string) string {
	return fmt.Sprintf(`Open the following URL in a browser, sign in with the China Mobile account that owns the files and approve the authorization:

%s

The authorization must reach the final success page (a page that only says "authorized" midway is not enough). Then return here and press Enter. If you are configuring rclone on a remote machine without a browser, forward the URL to a machine with one and complete it there.`, authPageURL)
}

// NewFs constructs an Fs from the path.
//
// root 一律是专属目录内的相对路径；专属目录 folderId 由 user/folder/query
// 查询获得并作为目录树的 trueRootID。
func NewFs(ctx context.Context, name, root string, m configmap.Mapper) (fs.Fs, error) {
	opt := new(Options)
	if err := configstruct.Set(m, opt); err != nil {
		return nil, err
	}
	if opt.AccessToken == "" || opt.ClawUID == "" {
		return nil, errors.New("cmcloud: access_token and claw_uid are required - run `rclone config` to set up this remote")
	}
	if opt.ChunkSize < minChunkSize {
		return nil, fmt.Errorf("cmcloud: chunk_size (%v) must be greater than or equal to %v", opt.ChunkSize, fs.SizeSuffix(minChunkSize))
	}
	if opt.UploadCutoff < 0 {
		return nil, errors.New("cmcloud: upload_cutoff must not be negative")
	}
	root = strings.Trim(root, "/")

	f := &Fs{
		name: name,
		root: root,
		opt:  *opt,
	}
	f.srvSetup(ctx)
	f.features = (&fs.Features{
		CaseInsensitive:         false,
		CanHaveEmptyDirectories: true,
	}).Fill(ctx, f)

	// 锚定专属目录
	folder, err := f.c.UserFolderQuery(ctx)
	if err != nil {
		return nil, fmt.Errorf("cmcloud: failed to query dedicated directory: %w", err)
	}
	f.dirCache = dircache.New(root, folder.FolderID, f)

	// root 路径不存在时按 rclone 约定处理：先假设它是一个文件，
	// 退到父目录验证；父目录也不存在则返回原 Fs（Mkdir 时再建）。
	err = f.dirCache.FindRoot(ctx, false)
	if err != nil {
		newRoot, remote := dircache.SplitPath(root)
		tempF := *f
		tempF.dirCache = dircache.New(newRoot, folder.FolderID, &tempF)
		tempF.root = newRoot
		err = tempF.dirCache.FindRoot(ctx, false)
		if err != nil {
			// root 不存在，返回原 Fs
			return f, nil
		}
		_, err = tempF.NewObject(ctx, remote)
		if err != nil {
			if errors.Is(err, fs.ErrorObjectNotFound) {
				// root 指向的名字不存在：当作普通根目录
				return f, nil
			}
			return nil, err
		}
		f.features.Fill(ctx, &tempF)
		f.dirCache = tempF.dirCache
		f.root = tempF.root
		// 返回指向父目录的 Fs + ErrorIsFile
		return f, fs.ErrorIsFile
	}
	return f, nil
}

// srvSetup 构造业务/认证 client 与 pacer。
func (f *Fs) srvSetup(ctx context.Context) {
	srv := rest.NewClient(fshttp.NewClient(ctx)).SetRoot(api.BusinessBaseURL)
	srv.SetErrorHandler(api.HTTPErrorHandler)
	authSrv := rest.NewClient(fshttp.NewClient(ctx)).SetRoot(api.TokenBaseURL)
	f.auth = api.NewAuth(f.opt.AccessToken, f.opt.ClawUID, authSrv)
	f.pacer = api.NewPacer(ctx)
	f.c = api.NewClient(srv, f.auth, f.pacer)
	f.client = fshttp.NewClient(ctx) // 预签名 PUT/GET 直传
}

// ------------------------------------------------------------

// FindLeaf finds a directory of name leaf in the folder with ID pathID
// (dircache.DirCacher 接口，leaf 为 rclone 标准名)。
func (f *Fs) FindLeaf(ctx context.Context, pathID, leaf string) (pathIDOut string, found bool, err error) {
	found, err = f.listAll(ctx, pathID, func(item *api.Item) bool {
		if item.IsFolder() && f.opt.Enc.ToStandardName(item.Name) == leaf {
			pathIDOut = item.FileID
			return true
		}
		return false
	})
	return pathIDOut, found, err
}

// CreateDir makes a directory with pathID as parent and name leaf
// (dircache.DirCacher 接口)。dircache 先查后建，不会对已存在目录
// 调用本方法（服务端对同名 createFolder 会静默改名为时间戳副本）。
func (f *Fs) CreateDir(ctx context.Context, pathID, leaf string) (newID string, err error) {
	res, err := f.c.CreateFolder(ctx, f.opt.Enc.FromStandardName(leaf), pathID)
	if err != nil {
		return "", err
	}
	return res.FileID, nil
}

// listAll 翻页列出 pathID 下的全部条目，对每个条目调用 fn；
// fn 返回 true 时提前退出（found=true）。
func (f *Fs) listAll(ctx context.Context, pathID string, fn func(item *api.Item) bool) (found bool, err error) {
	cursor := ""
	for {
		res, err := f.c.FileList(ctx, pathID, cursor)
		if err != nil {
			return false, err
		}
		for i := range res.Items {
			if fn(&res.Items[i]) {
				return true, nil
			}
		}
		// items 为空但 cursor 非空时仍需继续翻页（实测结论）
		cursor = res.NextPageCursor
		if cursor == "" {
			break
		}
	}
	return false, nil
}

// itemModTime 取条目的修改时间：优先 localUpdatedAt（上传时设置的
// 本地时间，是 ModTime 往返一致性的唯一载体），缺失时回退 updatedAt。
func itemModTime(item *api.Item) time.Time {
	for _, s := range []string{item.LocalUpdatedAt, item.UpdatedAt} {
		if s == "" {
			continue
		}
		if t, err := time.Parse(time.RFC3339, s); err == nil {
			return t
		}
	}
	return time.Time{}
}

// newObjectWithInfo 把服务端条目转换为 Object。
func (f *Fs) newObjectWithInfo(remote string, item *api.Item) *Object {
	o := &Object{
		fs:     f,
		remote: remote,
	}
	o.setMetaData(item)
	return o
}

// setMetaData sets the metadata from info
func (o *Object) setMetaData(item *api.Item) {
	o.hasMetaData = true
	o.id = item.FileID
	o.size = item.Size
	o.modTime = itemModTime(item)
	if item.ContentHashAlgorithm == "sha256" || item.ContentHashAlgorithm == "" {
		o.sha256 = item.ContentHash
	}
}

// readMetaDataForPath reads the metadata for the file at path.
// 服务端无按名查询接口，只能列出父目录找名。
func (f *Fs) readMetaDataForPath(ctx context.Context, remote string) (*api.Item, error) {
	leaf, directoryID, err := f.dirCache.FindPath(ctx, remote, false)
	if err != nil {
		if errors.Is(err, fs.ErrorDirNotFound) {
			return nil, fs.ErrorObjectNotFound
		}
		return nil, err
	}
	var item *api.Item
	_, err = f.listAll(ctx, directoryID, func(candidate *api.Item) bool {
		if !candidate.IsFolder() && f.opt.Enc.ToStandardName(candidate.Name) == leaf {
			item = candidate
			return true
		}
		return false
	})
	if err != nil {
		return nil, err
	}
	if item == nil {
		return nil, fs.ErrorObjectNotFound
	}
	return item, nil
}

// NewObject finds the Object at remote.  If it can't be found
// it returns the error fs.ErrorObjectNotFound.
func (f *Fs) NewObject(ctx context.Context, remote string) (fs.Object, error) {
	o := &Object{
		fs:     f,
		remote: remote,
	}
	err := o.readMetaData(ctx)
	if err != nil {
		return nil, err
	}
	return o, nil
}

// readMetaData gets the metadata if it hasn't already been fetched
func (o *Object) readMetaData(ctx context.Context) (err error) {
	if o.hasMetaData {
		return nil
	}
	item, err := o.fs.readMetaDataForPath(ctx, o.remote)
	if err != nil {
		return err
	}
	o.setMetaData(item)
	return nil
}

// List the objects and directories in dir into entries.
//
// dir should be "" to list the root, and should not have trailing slashes.
func (f *Fs) List(ctx context.Context, dir string) (entries fs.DirEntries, err error) {
	directoryID, err := f.dirCache.FindDir(ctx, dir, false)
	if err != nil {
		return nil, err
	}
	return f.listDir(ctx, dir, directoryID)
}

// listDir 翻页列出一个目录并组装 DirEntries，同时把子目录 ID
// 写入 dircache 供后续路径解析复用。
func (f *Fs) listDir(ctx context.Context, dir, directoryID string) (entries fs.DirEntries, err error) {
	cursor := ""
	for {
		res, err := f.c.FileList(ctx, directoryID, cursor)
		if err != nil {
			return nil, err
		}
		for i := range res.Items {
			item := &res.Items[i]
			remote := path.Join(dir, f.opt.Enc.ToStandardName(item.Name))
			if item.IsFolder() {
				f.dirCache.Put(remote, item.FileID)
				entries = append(entries, fs.NewDir(remote, itemModTime(item)).SetID(item.FileID))
			} else {
				entries = append(entries, f.newObjectWithInfo(remote, item))
			}
		}
		cursor = res.NextPageCursor
		if cursor == "" {
			break
		}
	}
	return entries, nil
}

// ListR lists the objects and directories of the Fs starting
// from dir recursively.
//
// 递归下钻：目录入队逐层展开，避免递归调用栈过深。
func (f *Fs) ListR(ctx context.Context, dir string, callback fs.ListRCallback) (err error) {
	lh := list.NewHelper(callback)
	type dirQueueItem struct {
		remote string
		id     string
	}
	directoryID, err := f.dirCache.FindDir(ctx, dir, false)
	if err != nil {
		return err
	}
	queue := []dirQueueItem{{remote: dir, id: directoryID}}
	for len(queue) > 0 {
		current := queue[0]
		queue = queue[1:]
		entries, err := f.listDir(ctx, current.remote, current.id)
		if err != nil {
			return err
		}
		for _, entry := range entries {
			if err = lh.Add(entry); err != nil {
				return err
			}
			if d, ok := entry.(fs.Directory); ok {
				queue = append(queue, dirQueueItem{remote: d.Remote(), id: d.ID()})
			}
		}
	}
	return lh.Flush()
}

// Mkdir creates the container if it doesn't exist.
//
// rclone 语义：Mkdir("") 是创建 Fs 根目录本身，必须幂等。
// dircache 的先查后建保证不会对已存在目录触发服务端 createFolder。
func (f *Fs) Mkdir(ctx context.Context, dir string) error {
	_, err := f.dirCache.FindDir(ctx, dir, true)
	return err
}

// Put the object
//
// Copy the reader in to the new object which is returned.
//
// The new object may have been created if an error is returned.
func (f *Fs) Put(ctx context.Context, in io.Reader, src fs.ObjectInfo, options ...fs.OpenOption) (fs.Object, error) {
	o := &Object{
		fs:     f,
		remote: src.Remote(),
	}
	return o, o.Update(ctx, in, src, options...)
}

// Copy src to this remote using server-side copy operations.
//
// batchCopy 只能把文件原名复制到目标目录，不支持改名：目标叶名与
// 源不同时返回 fs.ErrorCantCopy，让上层回退到上传复制。
// 目标已存在时服务端会静默加时间戳后缀（实测行为），必须提前拦截。
func (f *Fs) Copy(ctx context.Context, src fs.Object, remote string) (fs.Object, error) {
	srcObj, ok := src.(*Object)
	if !ok {
		fs.Debugf(src, "Can't copy - not same remote type")
		return nil, fs.ErrorCantCopy
	}
	if err := srcObj.readMetaData(ctx); err != nil {
		return nil, err
	}
	_, srcLeaf := dircache.SplitPath(srcObj.remote)
	_, dstLeaf := dircache.SplitPath(remote)
	if srcLeaf != dstLeaf {
		fs.Debugf(src, "Can't copy %q -> %q: platform can't copy to a different name", srcObj.remote, remote)
		return nil, fs.ErrorCantCopy
	}
	// 预检目标不存在（服务端复制同名冲突会静默改名，rclone 语义要求报错）
	if _, err := f.NewObject(ctx, remote); err == nil {
		return nil, fmt.Errorf("cmcloud: can't copy %q: destination exists and the platform can't overwrite files", remote)
	} else if !errors.Is(err, fs.ErrorObjectNotFound) {
		return nil, err
	}
	_, directoryID, err := f.dirCache.FindPath(ctx, remote, true)
	if err != nil {
		return nil, err
	}
	taskID, err := f.c.BatchCopy(ctx, []string{srcObj.id}, directoryID)
	if err != nil {
		return nil, err
	}
	if _, err = f.c.WaitForTask(ctx, taskID); err != nil {
		return nil, err
	}
	// 服务端复制后存在短暂可见性延迟，定位副本时重试几次
	var copied fs.Object
	for range copyLocateTries {
		copied, err = f.NewObject(ctx, remote)
		if err == nil {
			return copied, nil
		}
		if !errors.Is(err, fs.ErrorObjectNotFound) {
			return nil, fmt.Errorf("cmcloud: failed to locate copied file: %w", err)
		}
		if err = sleepContext(ctx, 500*time.Millisecond); err != nil {
			return nil, err
		}
	}
	return nil, fmt.Errorf("cmcloud: failed to locate copied file: %w", err)
}

// sleepContext 等待指定时长，可被 ctx 取消中断。
func sleepContext(ctx context.Context, d time.Duration) error {
	select {
	case <-ctx.Done():
		return ctx.Err()
	case <-time.After(d):
		return nil
	}
}

// ------------------------------------------------------------

// Fs returns the parent Fs
func (o *Object) Fs() fs.Info {
	return o.fs
}

// Return a string version
func (o *Object) String() string {
	if o == nil {
		return "<nil>"
	}
	return o.remote
}

// Remote returns the remote path
func (o *Object) Remote() string {
	return o.remote
}

// ID returns the ID of the Object if known, or "" if not
func (o *Object) ID() string {
	return o.id
}

// Hash returns the SHA-256 of an object returning a lowercase hex string
func (o *Object) Hash(ctx context.Context, t hash.Type) (string, error) {
	if t != hash.SHA256 {
		return "", hash.ErrUnsupported
	}
	return o.sha256, nil
}

// Size returns the size of an object in bytes
func (o *Object) Size() int64 {
	err := o.readMetaData(context.TODO())
	if err != nil {
		fs.Logf(o, "Failed to read metadata: %v", err)
		return 0
	}
	return o.size
}

// ModTime returns the modification time of the object
//
// It attempts to read the objects mtime and if that isn't present the
// LastModified returned in the http headers
func (o *Object) ModTime(ctx context.Context) time.Time {
	err := o.readMetaData(ctx)
	if err != nil {
		fs.Logf(o, "Failed to read metadata: %v", err)
		return time.Now()
	}
	return o.modTime
}

// SetModTime sets the modification time of the local fs object
//
// 平台不支持修改已有文件的时间（update 端点被屏蔽，local 时间只能
// 在上传时携带）。
func (o *Object) SetModTime(ctx context.Context, modTime time.Time) error {
	return fs.ErrorCantSetModTime
}

// Storable returns a boolean showing whether this object storable
func (o *Object) Storable() bool {
	return true
}

// Open an object for read
//
// 链路：getDownloadUrl 取预签名 GET 地址 → 直接流式读（S3 预签名
// 天然支持 Range）。地址有效期 1 小时，取一次即用。
func (o *Object) Open(ctx context.Context, options ...fs.OpenOption) (in io.ReadCloser, err error) {
	if err = o.readMetaData(ctx); err != nil {
		return nil, err
	}
	if o.id == "" {
		return nil, errors.New("cmcloud: can't download - no fileId")
	}
	fs.FixRangeOption(options, o.size)
	// Range 起点越过文件末尾时直接返回空内容（对齐 local backend 行为）
	for _, option := range options {
		if ro, ok := option.(*fs.RangeOption); ok && ro.Start >= o.size {
			return io.NopCloser(strings.NewReader("")), nil
		}
	}
	dl, err := o.fs.c.GetDownloadURL(ctx, o.id)
	if err != nil {
		return nil, err
	}
	var resp *http.Response
	err = o.fs.pacer.Call(func() (bool, error) {
		req, err := http.NewRequestWithContext(ctx, http.MethodGet, dl.URL, nil)
		if err != nil {
			return false, err
		}
		fs.OpenOptionAddHTTPHeaders(req.Header, options)
		resp, err = o.fs.client.Do(req)
		if err != nil {
			return fserrors.ShouldRetry(err), err
		}
		if resp.StatusCode != http.StatusOK && resp.StatusCode != http.StatusPartialContent {
			statusCode := resp.StatusCode
			_ = resp.Body.Close()
			resp = nil
			// 403 通常是预签名地址过期，交上层重试整个 Open（重新取地址）
			return statusCode == http.StatusForbidden || statusCode == http.StatusTooManyRequests || statusCode >= 500,
				fmt.Errorf("cmcloud: download failed: HTTP status %d", statusCode)
		}
		return false, nil
	})
	if err != nil {
		return nil, err
	}
	return resp.Body, nil
}

// Remove an object
//
// 服务端屏蔽了删除端点（01000005，实测结论）。Remove 是 fs.Object
// 接口的必备方法，只能返回错误；fstests 的删除用例在 config.yaml
// 的 ignore 列表里跳过。
func (o *Object) Remove(ctx context.Context) error {
	return fs.ErrorNotImplemented
}

// Rmdir removes the directory if it is empty
//
// 服务端屏蔽了删除端点。Rmdir 是 fs.Fs 接口的必备方法，只能返回错误。
func (f *Fs) Rmdir(ctx context.Context, dir string) error {
	return fs.ErrorNotImplemented
}

// DirCacheFlush resets the directory cache - used in testing as an
// optional interface
func (f *Fs) DirCacheFlush() {
	f.dirCache.ResetRoot()
}

// Check the interfaces are satisfied
var (
	_ fs.Fs              = (*Fs)(nil)
	_ fs.Copier          = (*Fs)(nil)
	_ fs.ListRer         = (*Fs)(nil)
	_ fs.DirCacheFlusher = (*Fs)(nil)
	_ fs.Object          = (*Object)(nil)
	_ fs.IDer            = (*Object)(nil)
)
